name: Validate

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: home-assistant/actions/hassfest@f6f29a7ee3fa0eccadf3620a7b9ee00ab54ec03b  # master @ 2026-04-07

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # v22.5.0
        with:
          category: integration
