name: Validate

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: home-assistant/actions/hassfest@4d8efb6e870e7d4bb5a39f72fbadc25a05cda49b  # master @ 2025-04

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: hacs/action@3b09cca1d5cd8b3e2cb02bbcd5da8aa72e74bd3a  # 24.10.1
        with:
          category: integration
